name: release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb

      - run: cargo-deb --deb-revision="$(date +%s)"

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/debian/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: iliabylich/ppa@notify
        with:
          token: ${{ secrets.PPA_TOKEN }}
